### ISSUE TITLE
Build fail in rustc 1.34

### ISSUE THREAD

**Issue by DCjanus** [DCjanus/cang-jie#1]
ref: 
+ https://github.com/tantivy-search/tantivy/issues/483
+ https://github.com/tantivy-search/tantivy/commit/6a547b0b5fb25a6f7ae9841f94084762be449b0b#diff-80398c5faae3c069e4e6aa2ed11b28c0R43
solution: work with tantivy 0.9

**Comment by DCjanus** [comment]
ref https://github.com/tantivy-search/tantivy/milestone/14

**Comment by fulmicoton** [comment]
It was released yesterday.

**Comment by DCjanus** [comment]
released 0.3.0
