### ISSUE TITLE
crates上的0.12仍然依赖tantivy0.14

### ISSUE THREAD

**Issue by darkskygit** [DCjanus/cang-jie#26]
![image](https://user-images.githubusercontent.com/25152247/126892221-778f9577-90ae-4841-bbb3-c7ccc09ba0c2.png)
但源码是升级了依赖再bump version的

**Comment by DCjanus** [comment]
我重新publish一次试试

**Comment by DCjanus** [comment]
感谢反馈，不确定是否是我的误操作，已经重新发布，并yank了 0.12.0
