### ISSUE TITLE
Bump version of tantivy dependency

### ISSUE THREAD

**Issue by Evian-Zhang** [DCjanus/cang-jie#27]
tantivy发布了0.16版本，根据其在[CHANGELOG](https://github.com/tantivy-search/tantivy/blob/main/CHANGELOG.md)中的描述，仅仅是bugfix，所以可以安全地bump version。

**Comment by DCjanus** [comment]
Closed by https://github.com/DCjanus/cang-jie/pull/28.

Thanks
